title: "Sathish's Portfolio"
description: "Data Analyst | Business Intelligence | Data Engineering"
remote_theme: pages-themes/architect@v0.2.0

author:
  name: Sathish Suresh
  email: ssures.work@outlook.com

# Social links
github_username: https://github.com/DataBySathish/
linkedin_username: https://www.linkedin.com/in/sathishsuresh/

# Plugins (required for remote themes)
plugins:
  - jekyll-remote-theme
