title: Sathish Suresh
description: “A curated portfolio showcasing my data analysis, visualization, 
and machine learning projects — highlighting skills in Python, SQL, and BI tools to extract insights and solve real-world problems.”
show_downloads: True
remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one


